### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'filtered_job'

### ISSUE THREAD

**Issue by eraffaelli** [hugomcfonseca/rundeck-executions-cleanup#3]
Hi,

First, thank you for providing a script to clean the rundeck job, it's hard to find a way to do it ;)

I've got a problem with the script while trying it. 

```bash
python executions_management.py -a xxxxxxxxxxxxxx  --ssl-enabled -m listing --db-host xx.xx.xx.xx --db-name rundeck01 --db-user rundeck01 --db-pass 
Traceback (most recent call last):
  File "executions_management.py", line 439, in <module>
    CONFIGS.filtered_project, CONFIGS.filtered_job, CONFIGS.only_running)
AttributeError: 'Namespace' object has no attribute 'filtered_job'
```
Am I required to filter the job? The --filtered-job is not recognized when I try it.

There is a problem with the readme, it's not really accurate on the commands (for example : --mode don't work, the help give --execution-mode or -m). The command --only-running is not recognized too.

Cheers
E.R

**Comment by hugomcfonseca** [comment]
Hi @eraffaelli,

About the **listing** execution mode, I am still working on it. For now, I was focused on Rundeck cleanup to run Rundeck cleanups on a daily basis through a Docker container.

About the unrecognized arguments, it misses some updates on it. Some of those options are not available anymore or are missing implementations (e.g., development of **listing** mode). I am going to update it as soon as possible and will refer this issue. 

Also, to perform an quick clean up, it needs to do some manual changes on Rundeck database and I will also include it in documentation. 

Thanks for feedback. I hope you enjoy it.

**Comment by eraffaelli** [comment]
Hi,
Thanks for the reply, I will wait with impatience. 👍

**Comment by hugomcfonseca** [comment]
Hello @eraffaelli,

Please, check now the [documentation](https://github.com/hugomcfonseca/rundeck-executions-management/blob/master-docker/readme.md).

I still didn't look to the problems in listing mode, I will work on this in the next days.
